# Generated by Django 5.2 on 2025-05-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Phone',
            new_name='phone',
        ),
    ]
