# Generated by Django 5.2 on 2025-05-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_phone_employee_phone'),
    ]

    operations = [
    ]
